batch_size: 2  # 设置批量大小
img_size: 512  # 输入图片大小
overlap: 64
epoches: 300
base_lr: 0.001  # 学习率
weight_decay: 2e-5
momentum: 0.9
power: 0.99
gpu_id: '0'
save_iter: 2
num_workers: 2
val_visual: True
image_driver: 'gdal'   #pillow, gdal
color_table: 0,0,0,255,255,255,0,255,0,0,0,255
loss_type: 'bce'
num_class: 1  # some parameters
thread: 0.5

resume_ckpt: 'E:\TempFiles\0401_files\UNet_v1\pth_UNet\valiou_best.pth'
model_name: 'UNet'  #
pretrained_model: 'C:\Users\Administrator\Downloads\swin_tiny_patch4_window7_224.pth'
extra_loss: False
model_experision: 'v1'

input_bands: 3
vis_graph: False
train_gt: 'dataset\CHN6-CUG\val\gt'
val_gt: 'dataset\CHN6-CUG\val\gt'
test_gt: 'dataset\CHN6-CUG\val\gt'

#data path
root_path: 'E:\TempFiles'
data_name: 'data_debug'
exp_name: '0401'

pred_path: 'test_result'