batch_size: 20  # 设置批量大小
use_gpu: True  # 是否使用use_gpu
img_size: 512  # 输入图片大小
overlap: 64
epoches: 800
base_lr: 0.001  # 学习率
weight_decay: 2e-5
momentum: 0.9
power: 0.99
gpu_id: '0,1'
loss_type: 'bce'
save_iter: 2
num_workers: 1
val_visual: True
image_driver: 'gdal'   #pillow, gdal
color_txt: 'CHN6-CUG/color_table_road.txt'
num_class: 1  # some parameters
thread: 0.4

model_name: 'DinkNet50_extra'  # ' unet, res_unet_psp, res_unet'
#pretrained_model: 'pretrained_models/hrnetv2_w64-b47cc881.pth'
pretrained_model: 'pretrained_models/resnet50_ram-a26f946b.pth'
extra_loss: True
model_experision: 'v1'

input_bands: 3
vis_graph: False
train_list: 'cug_seg-master/data/train_list.txt'
val_list: 'cug_seg-master/data/val_list.txt'
test_list: 'cug_seg-master/data/test_list.txt'
train_gt: 'CHN6-CUG/train/gt'
val_gt: 'CHN6-CUG/val/gt'

#data path
#root_path: 'F:\paper_list\CHN6-CUG_seg\CUG_seg'
root_path: '/nfs/project/netdisk/200/workspace/segmentation/private/dongsj/dongsj_224/dongsj/CUG_seg'
dataset: 'massroad'
exp_name: '1109'


save_path: 'result3'

#mean4: 0.472455, 0.320782, 0.318403, 0.357
#std4: 0.144, 0.151, 0.211, 0.195
#mean: 0.472455, 0.320782, 0.318403
#std: 0.215084, 0.408135, 0.409993  # 标准化参数
#save_dir = '../{}_files'.format(exp_name)
#save_dir_model = os.path.join(save_dir, model_name+'_'+model_experision)
#if os.path.exists(save_dir) is False:
#    os.mkdir(save_dir)
#if os.path.exists(save_dir_model) is False:
#    os.mkdir(save_dir_model)
#data_dir = os.path.join(save_dir, 'data_slice_{}'.format(dataset))
#train_path = os.path.join(root_data, 'train')
#train_gt = os.path.join(root_data, 'train_labels')
#test_gt = os.path.join(root_data, 'test_labels')
#output = os.path.join(save_dir_model, './result_{}/'.format(model_name))
#output_gray = os.path.join(save_dir_model, './result_gray_{}/'.format(model_name))
#model_dir = os.path.join(save_dir_model, './pth_{}/'.format(model_name))